services:
    Link4mailing_urlhelper:
        class: Zaeder\Link4mailingBundle\Service\UrlHelper
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
