services:
    Link4mailing_urlhelper:
        class: Zaeder\Link4mailingBundle\Service\UrlHelper
        arguments: ["@doctrine.orm.entity_manager", "@Link4mailing_autologin", "@router", "%zaederlink4mailingbundle.user_class%"]
            
    Link4mailing_autologin:
        class: Zaeder\Link4mailingBundle\Service\Autologin
        arguments: ["@doctrine.orm.entity_manager", "@security.context", "@fos_user.security.login_manager", "%zaederlink4mailingbundle.user_class%", "%fos_user.firewall_name%"]
