services:
    Link4mailing_urlhelper:
        class: Zaeder\Link4mailingBundle\Service\UrlHelper
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
            autologin: "@Link4mailing_autologin"
            
    Link4mailing_autologin:
        class: Zaeder\Link4mailingBundle\Service\Autologin
        arguments:
            container: "@service_container"
            entity_manager: "@doctrine.orm.entity_manager"
